# Generated by Django 6.0.6 on 2026-09-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_no', models.CharField(max_length=20, unique=True)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_mobile', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Duty', 'On Duty'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OPDRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('visit_type', models.CharField(choices=[('New', 'New'), ('Follow-up', 'Follow-up')], max_length=20)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10)),
                ('opd_status', models.CharField(choices=[('Waiting', 'Waiting'), ('In Consultation', 'In Consultation'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('visitor_type', models.CharField(choices=[('Patient Relative', 'Patient Relative'), ('Patient Friend', 'Patient Friend'), ('Doctor Visitor', 'Doctor Visitor'), ('Medical Representative', 'Medical Representative'), ('Vendor', 'Vendor'), ('Delivery Person', 'Delivery Person'), ('Maintenance Staff', 'Maintenance Staff'), ('Government Official', 'Government Official'), ('Job Applicant', 'Job Applicant'), ('Other', 'Other')], max_length=30)),
                ('purpose', models.CharField(choices=[('Meet Patient', 'Meet Patient'), ('Meet Doctor', 'Meet Doctor'), ('Medical Representative', 'Medical Representative'), ('Equipment Delivery', 'Equipment Delivery'), ('Maintenance Work', 'Maintenance Work'), ('Interview', 'Interview'), ('Submit Documents', 'Submit Documents'), ('Collect Reports', 'Collect Reports'), ('Administrative Work', 'Administrative Work'), ('Other', 'Other')], max_length=30)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(choices=[('general', 'General'), ('cardiac', 'Cardiac'), ('neuro', 'Neuro'), ('orthopedic', 'Orthopedic'), ('child_care', 'Child Care'), ('women_maternity', 'Women & Maternity'), ('gastro_kidney', 'Gastro & Kidney'), ('ent_eye', 'ENT & Eye'), ('skin_allergy', 'Skin & Allergy'), ('surgery_emergency', 'Surgery & Emergency')], max_length=100)),
                ('number_of_visitors', models.PositiveIntegerField(default=1)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Inside', 'Inside'), ('Left', 'Left')], default='Inside', max_length=10)),
            ],
        ),
    ]
